version: '2'

services:

  app:
    image: 'com.cosmetology.application:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - DB_SERVER=db
      - DB_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=root
    ports:
      - 8080:8080


  db:
    image: "postgres:13.1-alpine"
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
